doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            tsvector:    App\Infrastructure\Orm\Types\TsVector
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: sequence
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: Domain
        controller_resolver:
            auto_mapping: false
        dql:
            numeric_functions:
                RANDOM: DoctrineExtensions\Query\Sqlite\Random
                ROUND: DoctrineExtensions\Query\Mysql\Round
            datetime_functions:
                EXTRACT: DoctrineExtensions\Query\Postgresql\ExtractFunction
                TO_CHAR: DoctrineExtensions\Query\Postgresql\DateFormat
                NOW: DoctrineExtensions\Query\Mysql\Now
            string_functions:
                LPAD: DoctrineExtensions\Query\Mysql\Lpad
                CAST: DoctrineExtensions\Query\Mysql\Cast


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
