parameters:
    router.request_context.host: 'norldfinance.com'
    router.request_context.scheme: 'https'
    asset.request_context.secure: true
    email.admin: norldsite8@gmail.com
    NAME_SITE: 'NORLD FINANCE'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Http\EventSubscriber\RequestContextSubscriber:
        arguments:
            $twig: '@twig'
        tags:
            - { name: kernel.event_subscriber }
    App\Http\EventSubscriber\LocaleSubscriber:
         tags: [kernel.event_subscriber]
    
        
