# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    router.request_context.scheme: 'https'
    asset.request_context.secure: true
    email.admin: contact@norldfinance.com
    NAME_SITE: 'NORLD FINANCE'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Http\EventSubscriber\RequestContextSubscriber:
        arguments:
            $twig: '@twig'
        tags:
            - { name: kernel.event_subscriber }
    App\Http\EventSubscriber\LocaleSubscriber:
         tags: [kernel.event_subscriber]
